CREATE DATABASE greenlight;

\c greenlight;

CREATE ROLE greenlight WITH LOGIN PASSWORD 'pa55word';

CREATE EXTENSION IF NOT EXISTS citext;

GRANT ALL ON DATABASE mydb TO admin;

ALTER DATABASE mydb OWNER TO admin;